# -*- coding: utf-8 -*-
"""ClassWk8_1ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AMJMXgJMCKzh5cO-KSkzw6DXUOaOOCkO
"""

#Fancy Indexing
import numpy as np
rand=np.random.RandomState(0)
x=rand.randint(100,size=10)
print(x)

[x[3],x[7],x[2]]

ind=[3,7,2,5]
x[ind]

ind=np.array([[3,7],[2,5]])
x[ind]

x=np.arange(12).reshape((3,4))
x

row=np.array([0,1,2])
col=np.array([2,1,3])
x[row,col]

#Combined Indexing
print(x)

x[2,[2,0,1]]

#modifying values with fancy indexing
x=np.arange(10)
i=np.array([2,1,5,8])
x[i]=56
print(x)

#Sorting
x=np.array([2,1,3,4,9,5])
np.sort(x)

x.sort()
print(x)

x=np.array([2,1,3,4,9,5])
i=np.argsort(x)
print(i)

rand=np.random.RandomState(0)
x=rand.randint(0,10,(4,6))
print(x)

np.sort(x,axis=0) #sort each column

np.sort(x,axis=1) #sort each row

#Partial sorts
x=np.array([7,2,5,8,9,3,4,1]) #partitions the array, the elements have arbitrary order
np.partition(x,3)

#Structured Arrays
name=['Aryan','Kevin','Alvis','Adithya']
age=[20,21,22,21]
weight=[48.0,51.0,57.0,63.5]

x=np.zeros(4,dtype=int)
x

data=np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})
print(data.dtype)

data['name']=name
data['age']=age
data['weight']=weight
print(data)

#referring values by index or by name
print(data['name'])#getting all names
print(data[0])       #first row of data
print(data[-1]['name'])  #getting the name from the last row

data[data['age']<30]['name']

#Creating Structured Arrays
np.dtype({'names':('name','age','weight'),
          'formats':('U10','i4','f8')})

np.dtype({'names':('name','age','weight'),
          'formats':((np.str_,10),int,np.float32)})

np.dtype([('name','S10'),('age','i4'),('weight','f8')])

#Record Arrays
data['age']

data_rec=data.view(np.recarray)
data_rec.age

np.random.seed(0)
x=np.random.randn(100)

bins=np.linspace(-5,5,20)
counts=np.zeros_like(bins)
i=np.searchsorted(bins,x)
np.add.at(counts,i,1)

import matplotlib.pyplot as plt
plt.plot(bins,counts,linestyle='steps')