# -*- coding: utf-8 -*-
"""ClassWk8_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nl3a2KeOdYducmvDqbTXFQ9wq3GlUiwX
"""

import numpy as np
import pandas as pd
data=pd.Series([0.25,0.5,0.75,1.0]) #one dimensional array of indexed data
data #series of values and indices

data.values

data.index

print(data[1])
print(data[1:3])

#Pandas Series Vs Numpy Array
# Numpy has implicit indexing, pandas has explicitly defined index
# Index can be values of any desired type
data=pd.Series([0.25,0.5,0.75,1.0],
        index=['a','b','c','d' ])
data

data['d']

data=pd.Series([0.25,0.5,0.75,1.0],
               index=[2,5,3,7])
data

data[3]

course_dict={'MCA':'2Years',
             'BCA':'3 Years',
             'CME':'3 years',
             'MSC_CSA':'2 Years'}
course=pd.Series(course_dict)
course

course['MCA']

course['MCA':'BCA'] #Slicing

#Constructing Series objects
pd.Series(data)

pd.Series([2,4,6])

pd.Series(5,index=[100,200,300])

pd.Series({2:'a',1:'b',3:'c'})

pd.Series({2:'a',1:'b',3:'c'},index=[3,2])

#Pandas DataFrame object
# DataFrame is a generalization of Numpy array or Specialization of Python dictionary

pattern_dict={'MCA':'Trimester','BCA':'Semester','MSC_CSA':'Weekend','CME':'Semester'}
pattern=pd.Series(pattern_dict)
pattern

details=pd.DataFrame({'Course':course,'Pattern':pattern})
details

details.index

details.columns

# DataFrame as specialized dictionary
# dataframe maps a column name to a series of column data
details['Course']

#Constructing dataframe objects
pd.DataFrame(details,columns=['Course'])

pd.DataFrame([1,2,3],index=['a', 'b', 'c'])

np.array([(0,1,3)]).size

data=[{'a':i,'b':2*i}
      for i in range(3)]
pd.DataFrame(data)

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])